(() => {
  'use strict';

  const A={
    toggle:'com.yandex.smarthome.streamdock.toggle',
    lightPower:'com.yandex.smarthome.streamdock.light.power',
    brightness:'com.yandex.smarthome.streamdock.brightness',
    sensor:'com.yandex.smarthome.streamdock.sensor',
    sensorMulti:'com.yandex.smarthome.streamdock.sensor.multi',
    curtain:'com.yandex.smarthome.streamdock.curtain',
    vacuum:'com.yandex.smarthome.streamdock.vacuum.speed',
    climate:'com.yandex.smarthome.streamdock.climate.mode',
    kettle:'com.yandex.smarthome.streamdock.kettle.temperature',
    lightTemp:'com.yandex.smarthome.streamdock.light.temperature',
    colorDial:'com.yandex.smarthome.streamdock.light.color.dial',
    color:'com.yandex.smarthome.streamdock.light.color',
    lightPreset:'com.yandex.smarthome.streamdock.light.preset',
    mediaVolume:'com.yandex.smarthome.streamdock.media.volume',
    mediaChannel:'com.yandex.smarthome.streamdock.media.channel',
    dashboard:'com.yandex.smarthome.streamdock.dashboard',
    media:'com.yandex.smarthome.streamdock.media.command',
    scenario:'com.yandex.smarthome.streamdock.scenario'
  };
  const VERSION='1.0.0';
  const $=id=>document.getElementById(id);
  function installTextEditingShortcuts(){document.addEventListener('keydown',async e=>{const el=e.target;if(!el||el.disabled||el.readOnly)return;const textLike=el.tagName==='TEXTAREA'||(el.tagName==='INPUT'&&['','text','password','search','email','url','tel'].includes(String(el.type||'text').toLowerCase()));if(!textLike)return;const mod=e.metaKey||e.ctrlKey,key=String(e.key||'').toLowerCase();if(mod&&key==='a'){e.preventDefault();e.stopPropagation();el.select();return;}if(mod&&key==='c'){const s=Number(el.selectionStart)||0,n=Number(el.selectionEnd)||0,txt=String(el.value||'').slice(Math.min(s,n),Math.max(s,n));if(txt&&navigator.clipboard?.writeText){e.preventDefault();e.stopPropagation();try{await navigator.clipboard.writeText(txt);}catch(_){}}return;}if(mod&&key==='v'&&navigator.clipboard?.readText){e.preventDefault();e.stopPropagation();try{const txt=await navigator.clipboard.readText(),s=Number(el.selectionStart)||0,n=Number(el.selectionEnd)||0;el.setRangeText(txt,s,n,'end');el.dispatchEvent(new Event('input',{bubbles:true}));}catch(_){}return;}if((e.key==='Backspace'||e.key==='Delete')){try{let s=Number(el.selectionStart)||0,n=Number(el.selectionEnd)||0;if(s===n){if(mod){if(e.key==='Backspace')s=0;else n=String(el.value||'').length;}else if(e.key==='Backspace'&&s>0)s--;else if(e.key==='Delete'&&n<String(el.value||'').length)n++;else return;}e.preventDefault();e.stopPropagation();el.setRangeText('',s,n,'end');el.dispatchEvent(new Event('input',{bubbles:true}));}catch(_){}return;}},true);}

  let ws=null, action='', piUuid='';
  let refreshStateTimeout=null;
  let settings={deviceId:'',deviceName:'',targetType:'device',brightnessStep:5,brightnessDialStep:1,brightnessAcceleration:true,curtainStep:10,curtainDialStep:1,curtainAcceleration:true,curtainReverse:false,temperatureStep:5,colorTemperatureStep:250,propertyInstance:'',powerMode:'toggle',colorPreset:'white',mediaCommand:'power_toggle',mediaVolumeStep:1,scenarioId:'',scenarioName:'',sensorThresholdEnabled:false,sensorWarn:'',sensorDanger:'',sensorDirection:'high',combinedInstances:'',sensorDialStyle:'widget',climateModeInstance:'',presetName:'Пресет',presetPower:true,presetUseBrightness:true,presetBrightness:50,presetUseTemperature:false,presetTemperature:3000,presetColor:'none',scenarioDialSource:'favorites',infoTemplate:'home'};
  let globalSettings={token:'',actionRefreshSeconds:30};
  let devices=[], scenarios=[], dashboardDevices=[], dashboardGroups=[], dashboardScenarios=[];
  let backendReady=false,globalReady=false,loading=false,lastAutoToken='',dashboardWindow=null,lastStatus='Ожидание запуска…',lastStatusClass='';

  const els={
    device:$('device'),refresh:$('refresh'),refreshState:$('refreshState'),status:$('status'),meta:$('meta'),badge:$('backendBadge'),actionName:$('actionName'),deviceLabel:$('deviceLabel'),deviceSection:$('deviceSection'),scenarioSettings:$('scenarioSettings'),scenario:$('scenario'),deviceButtons:$('deviceButtons'),
    powerSettings:$('powerSettings'),powerMode:$('powerMode'),brightnessSettings:$('brightnessSettings'),brightnessStep:$('brightnessStep'),brightnessAcceleration:$('brightnessAcceleration'),precisionHint:$('precisionHint'),sensorSettings:$('sensorSettings'),sensorProperty:$('sensorProperty'),sensorHint:$('sensorHint'),sensorThresholdEnabled:$('sensorThresholdEnabled'),sensorWarn:$('sensorWarn'),sensorDanger:$('sensorDanger'),sensorDirection:$('sensorDirection'),combinedSensorSettings:$('combinedSensorSettings'),combinedProperties:$('combinedProperties'),sensorDialStyle:$('sensorDialStyle'),sensorSingleStyle:$('sensorSingleStyle'),curtainSettings:$('curtainSettings'),curtainStep:$('curtainStep'),curtainAcceleration:$('curtainAcceleration'),curtainReverse:$('curtainReverse'),curtainHint:$('curtainHint'),vacuumSettings:$('vacuumSettings'),climateSettings:$('climateSettings'),climateModeInstance:$('climateModeInstance'),kettleSettings:$('kettleSettings'),temperatureStep:$('temperatureStep'),temperatureHint:$('temperatureHint'),lightTempSettings:$('lightTempSettings'),colorTemperatureStep:$('colorTemperatureStep'),colorTemperatureHint:$('colorTemperatureHint'),colorDialSettings:$('colorDialSettings'),colorSettings:$('colorSettings'),colorPreset:$('colorPreset'),lightPresetSettings:$('lightPresetSettings'),presetName:$('presetName'),presetPower:$('presetPower'),presetUseBrightness:$('presetUseBrightness'),presetBrightness:$('presetBrightness'),presetUseTemperature:$('presetUseTemperature'),presetTemperature:$('presetTemperature'),presetColor:$('presetColor'),mediaVolumeSettings:$('mediaVolumeSettings'),mediaVolumeStep:$('mediaVolumeStep'),mediaSettings:$('mediaSettings'),mediaCommand:$('mediaCommand'),dashboardActionSettings:$('dashboardActionSettings'),scenarioDialSource:$('scenarioDialSource'),infoTemplate:$('infoTemplate')
  };

  function setStatus(text,cls=''){lastStatus=text;lastStatusClass=cls;els.status.textContent=text;els.status.className='status'+(cls?' '+cls:'');postDashboard('status',{text,cls,backendReady});}
  function send(obj){if(!ws||ws.readyState!==WebSocket.OPEN){setStatus('Связь со Stream Dock не установлена.','error');return false;}ws.send(JSON.stringify(obj));return true;}
  function sendPlugin(payload){return send({event:'sendToPlugin',action,context:piUuid,payload});}
  function pm(v){return ['toggle','on','off'].includes(String(v))?String(v):'toggle';}
  function targetKey(d){return `${d?.entityType==='group'?'group':'device'}:${d?.id||''}`;}
  function sensorStyleValue(){const el=action===A.sensor?els.sensorSingleStyle:els.sensorDialStyle;return ['minimal','widget'].includes(el?.value)?el.value:'widget';}

  function saveActionSettings(){
    const d=devices.find(x=>targetKey(x)===els.device.value);
    const sc=scenarios.find(x=>x.id===els.scenario.value);
    settings={...settings,
      deviceId:d?.id||settings.deviceId||'',deviceName:d?.name||settings.deviceName||'',targetType:d?.entityType==='group'?'group':'device',
      brightnessStep:Number(els.brightnessStep.value)||1,brightnessDialStep:[1,5,10,20].includes(Number(els.brightnessStep.value))?Number(els.brightnessStep.value):1,brightnessAcceleration:Boolean(els.brightnessAcceleration.checked),
      curtainStep:Number(els.curtainStep.value)||1,curtainDialStep:[1,5,10,20].includes(Number(els.curtainStep.value))?Number(els.curtainStep.value):1,curtainAcceleration:Boolean(els.curtainAcceleration.checked),curtainReverse:Boolean(els.curtainReverse.checked),
      temperatureStep:Math.max(1,Math.min(25,Number(els.temperatureStep.value)||5)),
      colorTemperatureStep:Math.max(50,Math.min(1000,Number(els.colorTemperatureStep.value)||250)),
      propertyInstance:els.sensorProperty.value||settings.propertyInstance||'',powerMode:pm(els.powerMode.value||settings.powerMode),
      sensorThresholdEnabled:Boolean(els.sensorThresholdEnabled.checked),sensorWarn:els.sensorWarn.value.trim(),sensorDanger:els.sensorDanger.value.trim(),sensorDirection:els.sensorDirection.value||'high',
      combinedInstances:Array.from(els.combinedProperties.selectedOptions||[]).map(o=>o.value).join(','),sensorDialStyle:sensorStyleValue(),climateModeInstance:els.climateModeInstance.value||settings.climateModeInstance||'',
      colorPreset:els.colorPreset.value||settings.colorPreset||'white',mediaCommand:els.mediaCommand.value||settings.mediaCommand||'power_toggle',mediaVolumeStep:Math.max(1,Math.min(20,Number(els.mediaVolumeStep.value)||1)),
      presetName:els.presetName.value.trim()||'Пресет',presetPower:Boolean(els.presetPower.checked),presetUseBrightness:Boolean(els.presetUseBrightness.checked),presetBrightness:Math.max(1,Math.min(100,Number(els.presetBrightness.value)||50)),presetUseTemperature:Boolean(els.presetUseTemperature.checked),presetTemperature:Math.max(1500,Math.min(10000,Number(els.presetTemperature.value)||3000)),presetColor:els.presetColor.value||'none',
      scenarioId:els.scenario.value||settings.scenarioId||'',scenarioName:sc?.name||settings.scenarioName||'',scenarioDialSource:els.scenarioDialSource?.value==='all'?'all':'favorites',infoTemplate:['home','climate','alerts','favorites'].includes(els.infoTemplate?.value)?els.infoTemplate.value:'home'
    };
    send({event:'setSettings',context:piUuid,payload:settings});
  }

  function saveGlobalToken(value){const clean=String(value||'').trim();globalSettings={...globalSettings,token:clean};globalReady=true;send({event:'setGlobalSettings',context:piUuid,payload:globalSettings});sendPlugin({command:'saveGlobalToken',token:clean});postDashboard('globalSettings',globalSettings);}

  function hideActionSettings(){['powerSettings','brightnessSettings','sensorSettings','combinedSensorSettings','curtainSettings','vacuumSettings','climateSettings','kettleSettings','lightTempSettings','colorDialSettings','colorSettings','lightPresetSettings','mediaVolumeSettings','mediaSettings','dashboardActionSettings','scenarioSettings'].forEach(id=>$(id).classList.add('hidden'));els.deviceSection.classList.remove('hidden');els.deviceButtons.classList.remove('hidden');}
  function displayActionName(){
    hideActionSettings();
    if(action===A.lightPower){els.actionName.textContent='Свет — Вкл/Выкл';els.deviceLabel.textContent='Лампа / группа света';els.powerSettings.classList.remove('hidden');}
    else if(action===A.brightness){els.actionName.textContent='Свет — Яркость';els.deviceLabel.textContent='Лампа / устройство с яркостью';els.brightnessSettings.classList.remove('hidden');}
    else if(action===A.sensor){els.actionName.textContent='Датчик — Показание';els.deviceLabel.textContent='Датчик / устройство';els.sensorSettings.classList.remove('hidden');}
    else if(action===A.sensorMulti){els.actionName.textContent='Датчик — Показатели';els.deviceLabel.textContent='Датчик / устройство';els.combinedSensorSettings.classList.remove('hidden');}
    else if(action===A.curtain){els.actionName.textContent='Шторы — Положение';els.deviceLabel.textContent='Шторы / жалюзи';els.curtainSettings.classList.remove('hidden');}
    else if(action===A.vacuum){els.actionName.textContent='Пылесос — Скорость';els.deviceLabel.textContent='Пылесос';els.vacuumSettings.classList.remove('hidden');}
    else if(action===A.climate){els.actionName.textContent='Очиститель / Вентилятор';els.deviceLabel.textContent='Очиститель / вентилятор';els.climateSettings.classList.remove('hidden');}
    else if(action===A.kettle){els.actionName.textContent='Чайник — Температура';els.deviceLabel.textContent='Чайник';els.kettleSettings.classList.remove('hidden');}
    else if(action===A.lightTemp){els.actionName.textContent='Свет — Температура';els.deviceLabel.textContent='Лампа / группа света';els.lightTempSettings.classList.remove('hidden');}
    else if(action===A.colorDial){els.actionName.textContent='Свет — Цвета (крутилка)';els.deviceLabel.textContent='Цветная лампа / группа';els.colorDialSettings.classList.remove('hidden');}
    else if(action===A.color){els.actionName.textContent='Свет — Цвет';els.deviceLabel.textContent='Цветная лампа';els.colorSettings.classList.remove('hidden');}
    else if(action===A.lightPreset){els.actionName.textContent='Свет — Пресет';els.deviceLabel.textContent='Лампа / группа света';els.lightPresetSettings.classList.remove('hidden');}
    else if(action===A.mediaVolume){els.actionName.textContent='Телевизор / ИК — Громкость';els.deviceLabel.textContent='ТВ / ИК-устройство';els.mediaVolumeSettings.classList.remove('hidden');}
    else if(action===A.mediaChannel){els.actionName.textContent='Телевизор / ИК — Каналы';els.deviceLabel.textContent='ТВ / ИК-устройство';}
    else if(action===A.dashboard){els.actionName.textContent='Умный дом — Панель / Сводка';els.deviceSection.classList.add('hidden');els.deviceButtons.classList.add('hidden');els.dashboardActionSettings.classList.remove('hidden');}
    else if(action===A.media){els.actionName.textContent='ИК / Пульт — Команда';els.deviceLabel.textContent='ИК-устройство';els.mediaSettings.classList.remove('hidden');}
    else if(action===A.scenario){els.actionName.textContent='Сценарий — Запустить / Крутилка';els.deviceSection.classList.add('hidden');els.scenarioSettings.classList.remove('hidden');els.deviceButtons.classList.add('hidden');}
    else{els.actionName.textContent='Устройство — Вкл/Выкл';els.deviceLabel.textContent='Устройство';els.powerSettings.classList.remove('hidden');}
  }

  function prettyType(t=''){if(t.startsWith('devices.types.light'))return'Освещение';if(t.startsWith('devices.types.vacuum_cleaner'))return'Пылесос';if(t.includes('openable.curtain'))return'Шторы';if(t.startsWith('devices.types.cooking.kettle'))return'Чайник';if(t.startsWith('devices.types.sensor'))return'Датчик';if(t.startsWith('devices.types.media_device.tv'))return'Телевизор / ИК';if(t.startsWith('devices.types.media_device'))return'Медиа / ИК';if(t.startsWith('devices.types.hub'))return'Хаб / пульт';if(t.startsWith('devices.types.socket'))return'Розетка';if(t.startsWith('devices.types.switch'))return'Выключатель';return t.replace('devices.types.','').replaceAll('.',' · ')||'Устройство';}
  function fmtProp(p){if(!p)return'—';const n=Number(p.value);const v=Number.isFinite(n)?String(Math.round(n*10)/10):String(p.value??'—');return v+(p.unitText?' '+p.unitText:'');}

  function populateSensorProperties(d,selected=''){els.sensorProperty.innerHTML='';const props=d?.properties||[];if(!props.length){els.sensorProperty.innerHTML='<option value="">Показания не найдены</option>';els.sensorProperty.disabled=true;return;}for(const p of props){const o=document.createElement('option');o.value=p.instance;o.textContent=`${p.label||p.instance} — ${fmtProp(p)}`;els.sensorProperty.append(o);}const target=props.some(p=>p.instance===selected)?selected:props[0].instance;els.sensorProperty.value=target;els.sensorProperty.disabled=false;settings.propertyInstance=target;const p=props.find(x=>x.instance===target);els.sensorHint.textContent=`${p?.label||target}: ${fmtProp(p)}. Обновляется каждые 30 секунд.`;}
  function populateCombinedProperties(d){const props=d?.properties||[];els.combinedProperties.innerHTML='';const selected=new Set(String(settings.combinedInstances||'').split(',').filter(Boolean));for(const p of props){const o=document.createElement('option');o.value=p.instance;o.textContent=`${p.label||p.instance} — ${fmtProp(p)}`;o.selected=selected.size?selected.has(p.instance):['temperature','humidity','co2_level','pm2.5_density'].includes(p.instance);els.combinedProperties.append(o);}if(props.length&&!Array.from(els.combinedProperties.selectedOptions).length){for(const o of Array.from(els.combinedProperties.options).slice(0,3))o.selected=true;}els.combinedProperties.disabled=!props.length;settings.combinedInstances=Array.from(els.combinedProperties.selectedOptions).map(o=>o.value).join(',');}
  function populateClimateModes(d){els.climateModeInstance.innerHTML='';const modes=d?.modes||[];for(const m of modes){const o=document.createElement('option');o.value=m.instance;o.textContent=CMD_MODE[m.instance]||m.instance;els.climateModeInstance.append(o);}const preferred=modes.find(m=>m.instance===settings.climateModeInstance)||modes.find(m=>['fan_speed','work_speed'].includes(m.instance))||modes[0];if(preferred){els.climateModeInstance.value=preferred.instance;settings.climateModeInstance=preferred.instance;}els.climateModeInstance.disabled=!modes.length;}

  const CMD_RANGE={volume:'Громкость',channel:'Канал',temperature:'Температура',brightness:'Яркость',open:'Открытие',humidity:'Влажность',heat:'Нагрев'};
  const CMD_TOGGLE={mute:'Звук',pause:'Пауза',oscillation:'Поворот',ionization:'Ионизация',backlight:'Подсветка',controls_locked:'Блокировка',keep_warm:'Поддержание температуры'};
  const CMD_MODE={input_source:'Источник',fan_speed:'Скорость вентилятора',thermostat:'Режим',work_speed:'Скорость',cleanup_mode:'Уборка',heat:'Нагрев',tea_mode:'Режим чая'};
  const CMD_VALUE={auto:'Авто',cool:'Охлаждение',heat:'Нагрев',fan_only:'Вентиляция',dry:'Осушение',low:'Низкая',medium:'Средняя',high:'Высокая',turbo:'Турбо',quiet:'Тихо',eco:'Эко',one:'Вход 1',two:'Вход 2',three:'Вход 3',four:'Вход 4',five:'Вход 5'};
  function mediaCommands(d){const out=[];if(d?.hasOnOff){if(d.onOffRetrievable)out.push(['power_toggle','Переключить питание']);out.push(['power_on','Включить']);out.push(['power_off','Выключить']);}for(const r of d?.ranges||[]){const label=CMD_RANGE[r.instance]||r.instance;const step=r.instance==='volume'?5:(r.instance==='channel'?1:Math.max(1,Number(r.precision)||1));out.push([`range_delta:${r.instance}:${step}`,`${label} +`]);out.push([`range_delta:${r.instance}:${-step}`,`${label} −`]);}for(const t of d?.toggles||[]){const label=CMD_TOGGLE[t.instance]||t.instance;out.push([`toggle:${t.instance}:on`,`${label}: Вкл`]);out.push([`toggle:${t.instance}:off`,`${label}: Выкл`]);}for(const m of d?.modes||[]){const label=CMD_MODE[m.instance]||m.instance;for(const v of m.modes||[])out.push([`mode:${m.instance}:${v}`,`${label}: ${CMD_VALUE[v]||v}`]);}return out;}
  function populateMediaCommands(d){els.mediaCommand.innerHTML='';const cmds=mediaCommands(d);if(!cmds.length){els.mediaCommand.innerHTML='<option value="">Команды не найдены</option>';els.mediaCommand.disabled=true;return;}for(const [id,label] of cmds){const o=document.createElement('option');o.value=id;o.textContent=label;els.mediaCommand.append(o);}const sel=cmds.some(x=>x[0]===settings.mediaCommand)?settings.mediaCommand:cmds[0][0];els.mediaCommand.value=sel;settings.mediaCommand=sel;els.mediaCommand.disabled=false;}

  function optionLabel(d){if([A.media,A.mediaVolume,A.mediaChannel].includes(action)){const type=prettyType(d.type);return `${d.name} · ${type}${d.isIrCandidate?' · ИК':''}`;}return d.name;}
  function groupedOptions(select,list,selectedKey){select.innerHTML='';const groupById=new Map(list.filter(d=>d.isGroup).map(g=>[String(g.id),g]));const rooms={};for(const d of list)(rooms[d.room||'Без комнаты']??=[]).push(d);for(const room of Object.keys(rooms).sort((a,b)=>a==='Без комнаты'?1:b==='Без комнаты'?-1:a.localeCompare(b,'ru'))){const og=document.createElement('optgroup');og.label=room;const gs=rooms[room].filter(d=>d.isGroup).sort((a,b)=>a.name.localeCompare(b.name,'ru'));const ds=rooms[room].filter(d=>!d.isGroup).sort((a,b)=>a.name.localeCompare(b.name,'ru'));for(const d of gs){const o=document.createElement('option');o.value=targetKey(d);o.textContent=`★ ${d.name} · группа${d.memberCount?` (${d.memberCount})`:''}`;if(o.value===selectedKey)o.selected=true;og.append(o);}for(const d of ds){const names=(d.groups||[]).map(id=>groupById.get(String(id))?.name).filter(Boolean);const o=document.createElement('option');o.value=targetKey(d);o.textContent=(names.length?'↳ ':'')+optionLabel(d)+(names.length?` · ${names.join(' / ')}`:'');if(o.value===selectedKey)o.selected=true;og.append(o);}select.append(og);}select.disabled=!list.length;}

  function renderMeta(d){if(!d){els.meta.textContent='';return;}const parts=[d.isGroup?`Группа · ${d.memberCount||0} устройств`:prettyType(d.type),d.room||'Без комнаты'];if(d.online===false)parts.push('НЕ В СЕТИ');if(d.brightness)parts.push(`яркость ${Math.round(Number(d.brightness.value)||0)}%`);if(d.open)parts.push(`открытие ${Math.round(Number(d.open.value)||0)}%`);if(d.temperature)parts.push(`температура ${d.temperature.min}–${d.temperature.max}${d.temperature.unitText||''}`);if(d.color?.supportsTemperature)parts.push(`свет ${d.color.temperatureMin}–${d.color.temperatureMax}K`);els.meta.textContent=parts.join(' · ');if(action===A.brightness&&d.brightness)els.precisionHint.textContent=`Диапазон ${d.brightness.min}–${d.brightness.max}%, шаг устройства ${d.brightness.precision}%.`;if(action===A.curtain&&d.open)els.curtainHint.textContent=`Диапазон ${d.open.min}–${d.open.max}%, шаг устройства ${d.open.precision}%.`;if(action===A.kettle&&d.temperature)els.temperatureHint.textContent=`Диапазон ${d.temperature.min}–${d.temperature.max}${d.temperature.unitText||'°C'}, шаг устройства ${d.temperature.precision}.`;if(action===A.lightTemp&&d.color)els.colorTemperatureHint.textContent=`Диапазон ${d.color.temperatureMin}–${d.color.temperatureMax} K.`;}

  function populate(list,selectedId='',selectedProp='',selectedType='device'){devices=Array.isArray(list)?list:[];const selected=devices.find(x=>x.id===selectedId&&(x.entityType||'device')===selectedType)||devices.find(x=>x.id===selectedId)||devices[0]||null;groupedOptions(els.device,devices,selected?targetKey(selected):'');if(selected){settings.deviceId=selected.id;settings.deviceName=selected.name;settings.targetType=selected.entityType==='group'?'group':'device';if(action===A.sensor)populateSensorProperties(selected,selectedProp);if(action===A.sensorMulti)populateCombinedProperties(selected);if(action===A.climate)populateClimateModes(selected);if(action===A.media)populateMediaCommands(selected);renderMeta(selected);}else{els.meta.textContent='Подходящие устройства не найдены.';}els.refreshState.disabled=!selected;}
  function populateScenarios(list,selectedId=''){scenarios=Array.isArray(list)?list:[];els.scenario.innerHTML='';for(const sc of scenarios){const o=document.createElement('option');o.value=sc.id;o.textContent=sc.name;if(sc.id===selectedId)o.selected=true;els.scenario.append(o);}if(scenarios.length&&!els.scenario.value)els.scenario.value=scenarios[0].id;els.scenario.disabled=!scenarios.length;const sc=scenarios.find(x=>x.id===els.scenario.value);if(sc){settings.scenarioId=sc.id;settings.scenarioName=sc.name;}}

  function requestDevices(force=false,suppliedToken=''){const t=String(suppliedToken||globalSettings.token||'').trim();if(!t){setStatus('Подключите аккаунт Яндекса в панели умного дома.','error');return;}loading=true;els.refresh.disabled=true;setStatus(action===A.scenario?'Получаю сценарии…':'Получаю список устройств…','loading');sendPlugin({command:'loadDevices',token:suppliedToken?t:'',force});}
  function maybeAutoLoad(){const t=String(globalSettings.token||'').trim();if(!backendReady||!globalReady||!t||lastAutoToken===t||loading)return;lastAutoToken=t;requestDevices(false);}

  function legacyDashboardPrefs(){try{const favorites=JSON.parse(localStorage.getItem('ysh.favorites')||'{}')||{};const collapsedRooms=JSON.parse(localStorage.getItem('ysh.collapsedRooms')||'{}')||{};const expandedGroups=JSON.parse(localStorage.getItem('ysh.expandedGroups')||'{}')||{};const compactMode=localStorage.getItem('ysh.compact')==='1';const activeRoom=localStorage.getItem('ysh.activeRoom')||'all';const meaningful=Object.keys(favorites).length||Object.keys(collapsedRooms).length||Object.keys(expandedGroups).length||compactMode||activeRoom!=='all';return meaningful?{favorites,collapsedRooms,expandedGroups,compactMode,activeRoom}:null;}catch(_){return null;}}
  function ensureDashboardPrefsMigrated(){if(globalSettings.dashboardPrefs&&typeof globalSettings.dashboardPrefs==='object')return;const prefs=legacyDashboardPrefs();if(!prefs)return;globalSettings={...globalSettings,dashboardPrefs:prefs};send({event:'setGlobalSettings',context:piUuid,payload:globalSettings});sendPlugin({command:'saveDashboardPrefs',dashboardPrefs:prefs});}
  function dashboardSnapshot(){return{version:VERSION,action,settings:{...settings},globalSettings:{...globalSettings},devices:dashboardDevices.slice(),groups:dashboardGroups.slice(),scenarios:dashboardScenarios.slice(),backendReady,status:{text:lastStatus,cls:lastStatusClass}};}
  function postDashboard(type,payload){if(!dashboardWindow||dashboardWindow.closed)return;try{dashboardWindow.postMessage({channel:'ysh',type,payload},'*');}catch(_){}}
  window.yshBridge={
    ready(){postDashboard('snapshot',dashboardSnapshot());},getSnapshot(){return dashboardSnapshot();},
    saveToken(value){const token=String(value||'').trim();saveGlobalToken(token);if(token){lastAutoToken=token;requestDevices(true,token);sendPlugin({command:'loadDashboardDevices',token,force:true});}},
    logout(){lastAutoToken='';saveGlobalToken('');},
    openExternal(url){sendPlugin({command:'openExternalUrl',url:String(url||'')});},
    savePreferences(prefs){globalSettings={...globalSettings,dashboardPrefs:(prefs&&typeof prefs==='object')?prefs:{}};send({event:'setGlobalSettings',context:piUuid,payload:globalSettings});sendPlugin({command:'saveDashboardPrefs',dashboardPrefs:globalSettings.dashboardPrefs});},
    setActionRefreshSeconds(value){const seconds=Number(value);globalSettings={...globalSettings,actionRefreshSeconds:seconds};send({event:'setGlobalSettings',context:piUuid,payload:globalSettings});sendPlugin({command:'setActionRefreshSeconds',actionRefreshSeconds:seconds});return Promise.resolve({ok:true,actionRefreshSeconds:seconds});},
    requestDevices(force=true,quiet=false){sendPlugin({command:'loadDashboardDevices',token:globalSettings.token||'',force:Boolean(force),quiet:Boolean(quiet)});},
    validateToken(value){sendPlugin({command:'validateToken',token:String(value||'').trim()});},
    command(payload){sendPlugin({command:'dashboardCommand',...(payload||{})});}
  };

  els.refresh.addEventListener('click',()=>requestDevices(true));
  els.refreshState.addEventListener('click',()=>{
    if(els.refreshState.disabled)return;
    els.refreshState.disabled=true;
    setStatus('Обновляю состояние…','loading');
    if(refreshStateTimeout)clearTimeout(refreshStateTimeout);
    refreshStateTimeout=setTimeout(()=>{
      refreshStateTimeout=null;
      els.refreshState.disabled=!els.device.value;
      setStatus('Обновление занимает слишком долго. Попробуйте «Обновить устройства».','error');
    },12000);
    if(!sendPlugin({command:'refreshState'})){
      if(refreshStateTimeout){clearTimeout(refreshStateTimeout);refreshStateTimeout=null;}
      els.refreshState.disabled=!els.device.value;
    }
  });
  els.device.addEventListener('change',()=>{const d=devices.find(x=>targetKey(x)===els.device.value);if(!d)return;settings.deviceId=d.id;settings.deviceName=d.name;settings.targetType=d.entityType==='group'?'group':'device';if(action===A.sensor)populateSensorProperties(d,'');if(action===A.sensorMulti)populateCombinedProperties(d);if(action===A.climate)populateClimateModes(d);if(action===A.media)populateMediaCommands(d);saveActionSettings();renderMeta(d);sendPlugin({command:'selectDevice',deviceId:d.id,deviceName:d.name,targetType:settings.targetType,brightnessStep:Number(els.brightnessStep.value)||1,brightnessDialStep:Number(els.brightnessStep.value)||1,brightnessAcceleration:els.brightnessAcceleration.checked,curtainStep:Number(els.curtainStep.value)||1,curtainDialStep:Number(els.curtainStep.value)||1,curtainAcceleration:els.curtainAcceleration.checked,curtainReverse:els.curtainReverse.checked,temperatureStep:Number(els.temperatureStep.value)||5,colorTemperatureStep:Number(els.colorTemperatureStep.value)||250,propertyInstance:els.sensorProperty.value||'',combinedInstances:Array.from(els.combinedProperties.selectedOptions||[]).map(o=>o.value).join(','),sensorDialStyle:sensorStyleValue(),climateModeInstance:els.climateModeInstance.value||'',powerMode:pm(els.powerMode.value),colorPreset:els.colorPreset.value,mediaCommand:els.mediaCommand.value,mediaVolumeStep:Number(els.mediaVolumeStep.value)||1,presetName:els.presetName.value.trim()||'Пресет',presetPower:els.presetPower.checked,presetUseBrightness:els.presetUseBrightness.checked,presetBrightness:Number(els.presetBrightness.value)||50,presetUseTemperature:els.presetUseTemperature.checked,presetTemperature:Number(els.presetTemperature.value)||3000,presetColor:els.presetColor.value||'none',sensorThresholdEnabled:els.sensorThresholdEnabled.checked,sensorWarn:els.sensorWarn.value.trim(),sensorDanger:els.sensorDanger.value.trim(),sensorDirection:els.sensorDirection.value||'high'});setStatus(`Выбрано: ${d.name}`,'ok');});
  els.scenario.addEventListener('change',()=>{const sc=scenarios.find(x=>x.id===els.scenario.value);if(!sc)return;settings.scenarioId=sc.id;settings.scenarioName=sc.name;saveActionSettings();sendPlugin({command:'selectScenario',scenarioId:sc.id,scenarioName:sc.name});setStatus(`Сценарий: ${sc.name}`,'ok');});
  els.scenarioDialSource?.addEventListener('change',()=>{settings.scenarioDialSource=els.scenarioDialSource.value==='all'?'all':'favorites';saveActionSettings();sendPlugin({command:'setScenarioDialSource',scenarioDialSource:settings.scenarioDialSource});setStatus(settings.scenarioDialSource==='favorites'?'Крутилка: только избранные сценарии.':'Крутилка: все сценарии.','ok');});
  els.infoTemplate?.addEventListener('change',()=>{settings.infoTemplate=['home','climate','alerts','favorites'].includes(els.infoTemplate.value)?els.infoTemplate.value:'home';saveActionSettings();sendPlugin({command:'setInfoTemplate',infoTemplate:settings.infoTemplate});setStatus('Шаблон информационной доски сохранён.','ok');});
  [els.brightnessStep,els.brightnessAcceleration].forEach(el=>el.addEventListener('change',()=>{const v=[1,5,10,20].includes(Number(els.brightnessStep.value))?Number(els.brightnessStep.value):1;els.brightnessStep.value=String(v);settings.brightnessDialStep=v;settings.brightnessStep=v;settings.brightnessAcceleration=els.brightnessAcceleration.checked;saveActionSettings();sendPlugin({command:'setBrightnessDial',brightnessDialStep:v,brightnessAcceleration:settings.brightnessAcceleration});setStatus(settings.brightnessAcceleration?`Яркость: базовый шаг ${v}%, ускорение включено.`:`Яркость: фиксированный шаг ${v}%.`,'ok');}));
  [els.curtainStep,els.curtainAcceleration].forEach(el=>el.addEventListener('change',()=>{const v=[1,5,10,20].includes(Number(els.curtainStep.value))?Number(els.curtainStep.value):1;els.curtainStep.value=String(v);settings.curtainDialStep=v;settings.curtainStep=v;settings.curtainAcceleration=els.curtainAcceleration.checked;saveActionSettings();sendPlugin({command:'setCurtainDial',curtainDialStep:v,curtainAcceleration:settings.curtainAcceleration});setStatus(settings.curtainAcceleration?`Шторы: базовый шаг ${v}%, ускорение включено.`:`Шторы: фиксированный шаг ${v}%.`,'ok');}));
  els.curtainReverse.addEventListener('change',()=>{settings.curtainReverse=els.curtainReverse.checked;saveActionSettings();sendPlugin({command:'setCurtainReverse',curtainReverse:settings.curtainReverse});setStatus(settings.curtainReverse?'Реверс включён.':'Реверс выключен.','ok');});
  els.temperatureStep.addEventListener('change',()=>{const v=Math.max(1,Math.min(25,Number(els.temperatureStep.value)||5));els.temperatureStep.value=v;settings.temperatureStep=v;saveActionSettings();sendPlugin({command:'setTemperatureStep',temperatureStep:v});});
  els.colorTemperatureStep.addEventListener('change',()=>{const v=Math.max(50,Math.min(1000,Number(els.colorTemperatureStep.value)||250));els.colorTemperatureStep.value=v;settings.colorTemperatureStep=v;saveActionSettings();sendPlugin({command:'setColorTemperatureStep',colorTemperatureStep:v});});
  els.sensorProperty.addEventListener('change',()=>{settings.propertyInstance=els.sensorProperty.value;saveActionSettings();sendPlugin({command:'setSensorProperty',propertyInstance:settings.propertyInstance});});
  [els.sensorThresholdEnabled,els.sensorWarn,els.sensorDanger,els.sensorDirection].forEach(el=>el.addEventListener('change',()=>{saveActionSettings();sendPlugin({command:'setSensorThresholds',sensorThresholdEnabled:els.sensorThresholdEnabled.checked,sensorWarn:els.sensorWarn.value.trim(),sensorDanger:els.sensorDanger.value.trim(),sensorDirection:els.sensorDirection.value||'high'});}));
  els.combinedProperties.addEventListener('change',()=>{saveActionSettings();sendPlugin({command:'setCombinedProperties',combinedInstances:Array.from(els.combinedProperties.selectedOptions).map(o=>o.value).join(',')});});
  [els.sensorDialStyle,els.sensorSingleStyle].filter(Boolean).forEach(el=>el.addEventListener('change',()=>{settings.sensorDialStyle=sensorStyleValue();saveActionSettings();sendPlugin({command:'setSensorDialStyle',sensorDialStyle:settings.sensorDialStyle});setStatus(settings.sensorDialStyle==='widget'?'Стиль отображения: Виджет':'Стиль отображения: Минималистичный','ok');}));
  els.climateModeInstance.addEventListener('change',()=>{saveActionSettings();sendPlugin({command:'setClimateMode',climateModeInstance:els.climateModeInstance.value});});
  [els.presetName,els.presetPower,els.presetUseBrightness,els.presetBrightness,els.presetUseTemperature,els.presetTemperature,els.presetColor].forEach(el=>el.addEventListener('change',()=>{saveActionSettings();sendPlugin({command:'setLightPreset',presetName:els.presetName.value.trim()||'Пресет',presetPower:els.presetPower.checked,presetUseBrightness:els.presetUseBrightness.checked,presetBrightness:Number(els.presetBrightness.value)||50,presetUseTemperature:els.presetUseTemperature.checked,presetTemperature:Number(els.presetTemperature.value)||3000,presetColor:els.presetColor.value||'none'});}));
  els.powerMode.addEventListener('change',()=>{settings.powerMode=pm(els.powerMode.value);saveActionSettings();sendPlugin({command:'setPowerMode',powerMode:settings.powerMode});});
  els.colorPreset.addEventListener('change',()=>{settings.colorPreset=els.colorPreset.value;saveActionSettings();sendPlugin({command:'setColorPreset',colorPreset:settings.colorPreset});});
  els.mediaCommand.addEventListener('change',()=>{settings.mediaCommand=els.mediaCommand.value;saveActionSettings();sendPlugin({command:'setMediaCommand',mediaCommand:settings.mediaCommand});});
  els.mediaVolumeStep.addEventListener('change',()=>{const v=Math.max(1,Math.min(20,Number(els.mediaVolumeStep.value)||1));els.mediaVolumeStep.value=String(v);settings.mediaVolumeStep=v;saveActionSettings();sendPlugin({command:'setMediaVolumeStep',mediaVolumeStep:v});});
  installTextEditingShortcuts();
  $('dashboard').addEventListener('click',()=>{ensureDashboardPrefsMigrated();if(backendReady){setStatus('Открываю панель…','loading');sendPlugin({command:'openDashboardWindow'});setTimeout(()=>setStatus('Панель открыта. Повторное нажатие вернёт уже открытое окно.','ok'),350);return;}if(dashboardWindow&&!dashboardWindow.closed){try{dashboardWindow.focus();postDashboard('snapshot',dashboardSnapshot());return;}catch(_){}}dashboardWindow=window.open('../../dashboard/index.html?lang=ru','YSHDashboard','width=1180,height=820,left=90,top=50');if(dashboardWindow)setTimeout(()=>{postDashboard('snapshot',dashboardSnapshot());if(globalSettings.token)sendPlugin({command:'loadDashboardDevices',force:false});},250);});


  function syncExtraControls(){
    els.sensorThresholdEnabled.checked=Boolean(settings.sensorThresholdEnabled);els.sensorWarn.value=settings.sensorWarn??'';els.sensorDanger.value=settings.sensorDanger??'';els.sensorDirection.value=settings.sensorDirection||'high';const ss=['minimal','widget'].includes(settings.sensorDialStyle)?settings.sensorDialStyle:'widget';els.sensorDialStyle.value=ss;if(els.sensorSingleStyle)els.sensorSingleStyle.value=ss;if(els.brightnessAcceleration)els.brightnessAcceleration.checked=settings.brightnessAcceleration!==false;if(els.curtainAcceleration)els.curtainAcceleration.checked=settings.curtainAcceleration!==false;
    els.presetName.value=settings.presetName||'Пресет';els.presetPower.checked=settings.presetPower!==false;els.presetUseBrightness.checked=settings.presetUseBrightness!==false;els.presetBrightness.value=Number(settings.presetBrightness)||50;els.presetUseTemperature.checked=Boolean(settings.presetUseTemperature);els.presetTemperature.value=Number(settings.presetTemperature)||3000;els.presetColor.value=settings.presetColor||'none';if(els.scenarioDialSource)els.scenarioDialSource.value=settings.scenarioDialSource==='all'?'all':'favorites';if(els.infoTemplate)els.infoTemplate.value=['home','climate','alerts','favorites'].includes(settings.infoTemplate)?settings.infoTemplate:'home';
  }
  window.connectElgatoStreamDeckSocket=(port,uuid,registerEvent,info,actionInfo)=>{
    piUuid=uuid;try{const a=JSON.parse(actionInfo||'{}');action=a.action||'';settings={...settings,...(a.payload?.settings||a.settings||{})};}catch(_){}
    settings.brightnessStep=Number(settings.brightnessStep)||5;settings.brightnessDialStep=[1,5,10,20].includes(Number(settings.brightnessDialStep))?Number(settings.brightnessDialStep):1;settings.brightnessAcceleration=settings.brightnessAcceleration!==false;settings.curtainStep=Number(settings.curtainStep)||10;settings.curtainDialStep=[1,5,10,20].includes(Number(settings.curtainDialStep))?Number(settings.curtainDialStep):1;settings.curtainAcceleration=settings.curtainAcceleration!==false;settings.curtainReverse=Boolean(settings.curtainReverse);settings.temperatureStep=Number(settings.temperatureStep)||5;settings.colorTemperatureStep=Number(settings.colorTemperatureStep)||250;settings.mediaVolumeStep=Math.max(1,Math.min(20,Number(settings.mediaVolumeStep)||1));settings.sensorDialStyle=['minimal','widget'].includes(settings.sensorDialStyle)?settings.sensorDialStyle:'widget';settings.scenarioDialSource=settings.scenarioDialSource==='all'?'all':'favorites';settings.infoTemplate=['home','climate','alerts','favorites'].includes(settings.infoTemplate)?settings.infoTemplate:'home';settings.powerMode=pm(settings.powerMode);settings.targetType=settings.targetType==='group'?'group':'device';
    displayActionName();syncExtraControls();els.brightnessStep.value=String(settings.brightnessDialStep);els.curtainStep.value=String(settings.curtainDialStep);els.curtainReverse.checked=settings.curtainReverse;els.temperatureStep.value=settings.temperatureStep;els.colorTemperatureStep.value=settings.colorTemperatureStep;els.mediaVolumeStep.value=String(settings.mediaVolumeStep);els.powerMode.value=settings.powerMode;els.colorPreset.value=settings.colorPreset||'white';
    ws=new WebSocket('ws://127.0.0.1:'+port);
    ws.onopen=()=>{send({event:registerEvent,uuid:piUuid});send({event:'getSettings',context:piUuid});send({event:'getGlobalSettings',context:piUuid});};
    ws.onmessage=evt=>{let data;try{data=JSON.parse(evt.data);}catch(_){return;}
      if(data.event==='didReceiveSettings'){const incoming=data.payload?.settings||{};const legacy=String(incoming.token||'').trim();settings={...settings,...incoming};settings.brightnessDialStep=[1,5,10,20].includes(Number(settings.brightnessDialStep))?Number(settings.brightnessDialStep):1;settings.brightnessAcceleration=settings.brightnessAcceleration!==false;settings.curtainDialStep=[1,5,10,20].includes(Number(settings.curtainDialStep))?Number(settings.curtainDialStep):1;settings.curtainAcceleration=settings.curtainAcceleration!==false;settings.sensorDialStyle=['minimal','widget'].includes(settings.sensorDialStyle)?settings.sensorDialStyle:'widget';settings.scenarioDialSource=settings.scenarioDialSource==='all'?'all':'favorites';settings.infoTemplate=['home','climate','alerts','favorites'].includes(settings.infoTemplate)?settings.infoTemplate:'home';settings.powerMode=pm(settings.powerMode);settings.targetType=settings.targetType==='group'?'group':'device';syncExtraControls();els.brightnessStep.value=String(settings.brightnessDialStep||1);els.curtainStep.value=String(settings.curtainDialStep||1);els.curtainReverse.checked=Boolean(settings.curtainReverse);els.temperatureStep.value=Number(settings.temperatureStep)||5;els.colorTemperatureStep.value=Number(settings.colorTemperatureStep)||250;els.mediaVolumeStep.value=String(Math.max(1,Math.min(20,Number(settings.mediaVolumeStep)||1)));els.powerMode.value=settings.powerMode;els.colorPreset.value=settings.colorPreset||'white';if(legacy&&globalReady&&!globalSettings.token){saveGlobalToken(legacy);}return;}
      if(data.event==='didReceiveGlobalSettings'){globalSettings={token:'',actionRefreshSeconds:30,...(data.payload?.settings||{})};globalSettings.token=String(globalSettings.token||'').trim();globalReady=true;ensureDashboardPrefsMigrated();postDashboard('globalSettings',globalSettings);maybeAutoLoad();return;}
      if(data.event!=='sendToPropertyInspector')return;const p=data.payload||{};postDashboard('event',p);
      if(p.type==='backendReady'){backendReady=true;els.badge.textContent='Backend OK';els.badge.className='badge ok';setStatus(p.message||'Backend запущен.','ok');maybeAutoLoad();}
      else if(p.type==='loading'){loading=true;els.refresh.disabled=true;setStatus(action===A.scenario?'Запрашиваю сценарии…':'Запрашиваю устройства…','loading');}
      else if(p.type==='devices'){loading=false;populate(p.devices,p.selectedDeviceId||settings.deviceId,p.selectedPropertyInstance||settings.propertyInstance,p.selectedTargetType||settings.targetType||'device');els.refresh.disabled=false;setStatus(p.message||'Устройства загружены.','ok');saveActionSettings();}
      else if(p.type==='scenarios'){loading=false;populateScenarios(p.scenarios,p.selectedScenarioId||settings.scenarioId);setStatus(p.message||'Сценарии загружены.','ok');saveActionSettings();}
      else if(p.type==='selected'){setStatus(`Выбрано: ${p.deviceName||p.deviceId}`,'ok');}
      else if(p.type==='sensorSnapshot'){const d=devices.find(x=>targetKey(x)===els.device.value);if(d&&Array.isArray(p.properties))d.properties=p.properties;if(action===A.sensor&&d){populateSensorProperties(d,settings.propertyInstance);renderMeta(d);}if(action===A.sensorMulti&&d){populateCombinedProperties(d);renderMeta(d);}}
      else if(p.type==='stateRefreshed'){if(refreshStateTimeout){clearTimeout(refreshStateTimeout);refreshStateTimeout=null;}els.refreshState.disabled=!els.device.value;setStatus(p.message||'Состояние обновлено.','ok');}
      else if(p.type==='actionRefreshChanged'){globalSettings={...globalSettings,actionRefreshSeconds:Number(p.actionRefreshSeconds)||0};postDashboard('globalSettings',globalSettings);}
      else if(p.type==='error'){if(refreshStateTimeout){clearTimeout(refreshStateTimeout);refreshStateTimeout=null;}loading=false;els.refresh.disabled=!globalSettings.token;els.refreshState.disabled=!els.device.value;setStatus(p.message||'Ошибка.','error');}
      else if(p.type==='dashboardLoading')postDashboard('dashboardLoading',p);
      else if(p.type==='dashboardDevices'){dashboardDevices=Array.isArray(p.devices)?p.devices:[];dashboardGroups=Array.isArray(p.groups)?p.groups:[];dashboardScenarios=Array.isArray(p.scenarios)?p.scenarios:[];postDashboard('dashboardDevices',p);}
      else if(p.type==='dashboardError')postDashboard('dashboardError',p);
      else if(p.type==='dashboardCommandResult')postDashboard('dashboardCommandResult',p);
      else if(p.type==='tokenStatus')postDashboard('tokenStatus',p);
    };
    ws.onerror=()=>{backendReady=false;els.badge.textContent='Нет связи';els.badge.className='badge error';setStatus('Ошибка WebSocket со Stream Dock.','error');};
  };
})();
